<?php
$title = 'Celulares';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('celular', array('action'=>'add'));?>">Cadastrar novo celular</a>
</p>

<table class="table">
<tr>
    <th>Marca</th>
    <th>Modelo</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($celulares as $celular) : ?>
<tr>
    <td><?php echo $this->escapeHtml($celular->marca);?></td>
    <td><?php echo $this->escapeHtml($celular->modelo);?></td>
    <td>
        <a href="<?php echo $this->url('celular',
            array('action'=>'edit', 'id' => $celular->id));?>">Editar</a>
        <a href="<?php echo $this->url('celular',
            array('action'=>'delete', 'id' => $celular->id));?>">Deletar</a>
    </td>
</tr>
<?php endforeach; ?>
</table>